CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	USER_ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING(255) NOT NULL,
	LOGIN CHARACTER VARYING(255) NOT NULL,
	USER_NAME CHARACTER VARYING(255),
	BIRTHDAY DATE,
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_FRIENDS (
	USER_ID INTEGER NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	FRIEND_STATUS CHARACTER VARYING NOT NULL,
	CONSTRAINT USER_FRIENDS_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
	GENRE_ID INTEGER NOT NULL AUTO_INCREMENT,
	GENRE_NAME CHARACTER VARYING(14) NOT NULL,
	CONSTRAINT CONSTRAINT_7 PRIMARY KEY (GENRE_ID),
	CONSTRAINT CONSTRAINT_7D UNIQUE (GENRE_NAME)
);

CREATE TABLE IF NOT EXISTS PUBLIC.MPA (
	MPA_ID INTEGER NOT NULL AUTO_INCREMENT,
	MPA_NAME CHARACTER VARYING(5) NOT NULL,
	CONSTRAINT CONSTRAINT_1 PRIMARY KEY (MPA_ID),
	CONSTRAINT CONSTRAINT_12 UNIQUE (MPA_NAME)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	FILM_ID INTEGER NOT NULL AUTO_INCREMENT,
	FILM_NAME CHARACTER VARYING(255) NOT NULL,
	DESCRIPTION CHARACTER VARYING(200),
	RELEASE_DATE DATE,
	DURATION INTEGER,
	MPA_ID INTEGER NOT NULL,
	CONSTRAINT CONSTRAINT_3 PRIMARY KEY (FILM_ID),
	CONSTRAINT FILMS_MPA_ID_FK FOREIGN KEY (MPA_ID) REFERENCES PUBLIC.MPA(MPA_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRES (
	FILM_ID INTEGER NOT NULL,
	GENRE_ID INTEGER NOT NULL,
	CONSTRAINT FILM_GENRES_FILM_ID_FK_2 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FILM_GENRES_GENRE_ID_FK_1 FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRES(GENRE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_LIKES (
	FILM_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	CONSTRAINT FILM_LIKES_FILM_ID_FK_1 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FILM_LIKES_USER_ID_FK_2 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);